name: CI/CD Pipeline PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP for coverage
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Debug phpunit.xml
        run: cat phpunit.xml
      
      - name: Grant execute permission to phpunit
        run: chmod +x ./vendor/bin/phpunit
      
      - name: Run tests and generate coverage report
        run: >
          ./vendor/bin/phpunit 
          --coverage-clover clover.xml 
          --coverage-filter app

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with: # <-- Token harus berada di dalam 'with:'
          args: >
            -Dsonar.organization=aqilalfa
            -Dsonar.projectKey=aqilalfa_scxlab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: sonarcloud
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
      - name: Deploy via Docker Compose
        run: docker-compose up -d --build