name: CI/CD Pipeline PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Tahap style-check telah dihapus

  # 1. Static Analysis (SonarCloud)
  sonarcloud:
    # "needs: style-check" dihapus, job ini berjalan pertama
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      # Langkah baru: Berikan izin eksekusi ke PHPUnit
      - name: Grant execute permission to phpunit
        run: chmod +x ./vendor/bin/phpunit
      
      # Menjalankan tes dan membuat laporan coverage
      - name: Run tests and generate coverage report
        run: ./vendor/bin/phpunit --coverage-clover clover.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # 2. Deployment (jika semua lolos)
  deploy:
    needs: sonarcloud
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
      - name: Deploy via Docker Compose
        run: docker-compose up -d --build